"""empty message

Revision ID: 0b3ebefb936a
Revises: e3302724b354
Create Date: 2019-03-22 08:56:43.782334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3ebefb936a'
down_revision = 'e3302724b354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('kota', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'kota')
    # ### end Alembic commands ###
