"""empty message

Revision ID: 15c83b7c1422
Revises: 219558c6bdf3
Create Date: 2019-03-18 06:39:54.952596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c83b7c1422'
down_revision = '219558c6bdf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('kadaluwarsa', sa.String(length=100), nullable=True))
    op.add_column('item', sa.Column('terjual', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'terjual')
    op.drop_column('item', 'kadaluwarsa')
    # ### end Alembic commands ###
