"""empty message

Revision ID: 219558c6bdf3
Revises: 6ff78799cc6f
Create Date: 2019-03-17 11:29:41.981646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219558c6bdf3'
down_revision = '6ff78799cc6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('urlimage', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'urlimage')
    # ### end Alembic commands ###
