"""empty message

Revision ID: 6ff78799cc6f
Revises: 414a940d128c
Create Date: 2019-03-17 09:32:53.307269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff78799cc6f'
down_revision = '414a940d128c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('stok', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('urlimages', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'urlimages')
    op.drop_column('item', 'stok')
    # ### end Alembic commands ###
