"""empty message

Revision ID: 86e41362a3fd
Revises: d8b5da5b2397
Create Date: 2019-03-21 20:22:41.943729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e41362a3fd'
down_revision = 'd8b5da5b2397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('transaction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'transaction')
    # ### end Alembic commands ###
