"""empty message

Revision ID: 965b0d8424c9
Revises: b561637760a3
Create Date: 2019-03-23 19:11:44.831667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965b0d8424c9'
down_revision = 'b561637760a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('owner_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'owner_id')
    # ### end Alembic commands ###
