"""empty message

Revision ID: d8b5da5b2397
Revises: de9379453ae7
Create Date: 2019-03-21 20:12:47.746625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b5da5b2397'
down_revision = 'de9379453ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'qty')
    # ### end Alembic commands ###
