"""empty message

Revision ID: de9379453ae7
Revises: 15c83b7c1422
Create Date: 2019-03-21 09:16:00.799010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9379453ae7'
down_revision = '15c83b7c1422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('berat', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('urlimage', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'urlimage')
    op.drop_column('cart', 'berat')
    # ### end Alembic commands ###
