"""empty message

Revision ID: e3302724b354
Revises: 86e41362a3fd
Create Date: 2019-03-21 21:24:04.168996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3302724b354'
down_revision = '86e41362a3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('status', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'status')
    # ### end Alembic commands ###
