"""empty message

Revision ID: ed2fd7ac0ce7
Revises: 965b0d8424c9
Create Date: 2019-03-24 11:52:23.037327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2fd7ac0ce7'
down_revision = '965b0d8424c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('deliver', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'deliver')
    # ### end Alembic commands ###
